name: Main Server Merge
on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v3

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install dependencies # 의존 파일 설치
        run: pnpm install

      # - name: Set .env from secrets
      #   run: |
      #     echo "${{ secrets.MAIN_ENV }}" > .env
      # - name: cat env file
      #   run: cat .env

      - name: Generate wbuild # React Build
        run: pnpm build

      #     - name: file copy
      #       uses: actions/upload-artifact@v3
      #       with:
      #         name: build
      #         path: build
      # deploy:
      #   needs: build
      #   runs-on: ubuntu-latest
      #   steps:
      #     - name: file download
      #       uses: actions/download-artifact@v3
      #       with:
      #         name: build
      #         path: build
      # - name: Upload to S3
